### ISSUE TITLE
Spinnaker broken on angular 1.2.9

### ISSUE THREAD

**Issue by RWOverdijk** [xdissent/spinnaker#2]
I get the following error in my console:

```
TypeError: Object #<SocketNamespace> has no method 'get'
    at request (http://127.0.0.1:1224/scripts/common.js:27789:25)
    at Function.<anonymous> (http://127.0.0.1:1224/scripts/common.js:27844:23)
    at new WidgetListCtrl (http://127.0.0.1:1224/scripts/home.js:10:27)
    at invoke (http://127.0.0.1:1224/scripts/common.js:3710:17)
    at Object.instantiate (http://127.0.0.1:1224/scripts/common.js:3721:23)
    at http://127.0.0.1:1224/scripts/common.js:6772:28
    at http://127.0.0.1:1224/scripts/common.js:6185:34
    at forEach (http://127.0.0.1:1224/scripts/common.js:310:20)
    at nodeLinkFn (http://127.0.0.1:1224/scripts/common.js:6172:11)
    at compositeLinkFn (http://127.0.0.1:1224/scripts/common.js:5636:15) 
```

I'm using angular 1.2.9 and followed the instructions in the readme.

The reason seems to be that you depend on sails.io.js. Wouldn't it be very easy to implement in this repo?

**Update:**
If you're going to respond to this issue.. Would you also mind explaining a bit more about how you've set this up? So, when I remove an element from my scope, will spinnaker still have a reference to it in memory?

**Comment by RWOverdijk** [comment]
Thanks..
